# This is a TOML configuration file.

title = "My New Project"

[base]
  DOMAIN="https://api.huobi.pro"

[base.API]
  # 获取交易对信息
  symbols="/v2/settings/common/symbols"
  # 获取当前市场状态
  market_status="/v2/market-status"
  # 获取所有币种
  currencies="/v2/settings/common/currencies"

[base.API.request.symbols]
  params=["t"]
  method="GET"


[base.API.request.market_status]
  params=""
  method="GET"


[base.API.request.currencies]
    params=""
    method="GET"